baekjoon/shim/Java/알고리즘_분류/함수/n_1065.java, baekjoon/shim/Java/알고리즘_분류/함수/n_15596.java, baekjoon/shim/Java/알고리즘_분류/함수/n_4673.java, baekjoon/shim/Python/알고리즘_분류/함수/n_1065.py, baekjoon/shim/Python/알고리즘_분류/함수/n_15596.py, baekjoon/shim/Python/알고리즘_분류/함수/n_4673.py, programmers/shim/Java/level1/20220517_없는_숫자_더하기.java
(python, java) 20220517_baekjoon 3문제 완료
=> 20220517_baekjoon

programmers/shim/Java/level1/20220518_음양_더하기.java, programmers/shim/Python/level1/20220518_음양_더하기.py
=> [SJJ]2022.05.18

programmers/shim/Java/level1/20220519_내적.java, programmers/shim/Python/level1/20220519_내적.py
(python, java) 2022.05.19 programmers 완료
=> [SJJ]2022.05.19

baekjoon/shim/Java/알고리즘_분류/문자열/n_1316.java, baekjoon/shim/Java/알고리즘_분류/문자열/n_2941.java, baekjoon/shim/Java/알고리즘_분류/문자열/n_5622.java, baekjoon/shim/Python/알고리즘_분류/문자열/n_1316.py, baekjoon/shim/Python/알고리즘_분류/문자열/n_2941.py, baekjoon/shim/Python/알고리즘_분류/문자열/n_5622.py
(python, java) 2022.05.20 baekjoon 3문제 완료
=> [SJJ]2022.05.20

baekjoon/shim/Java/알고리즘_분류/기본_수학_1/n_1712.java, baekjoon/shim/Java/알고리즘_분류/기본_수학_1/n_2292.java, baekjoon/shim/Java/알고리즘_분류/반복문/n_1110.java, baekjoon/shim/Python/알고리즘_분류/기본_수학_1/n_1712.py, baekjoon/shim/Python/알고리즘_분류/기본_수학_1/n_2292.py, baekjoon/shim/Python/알고리즘_분류/반복문/n_1110.py
(python, java) 2022.05.23 baekjoon 3문제 완료
=> [SJJ]2022.05.23

baekjoon/jieun/220524/10250.py, baekjoon/jieun/220524/1193.py, baekjoon/jieun/220524/2869.py, programmers/jieun/220524/모의고사.py
=> [jieun]2022.05.24

baekjoon/shim/Java/알고리즘_분류/기본_수학_1/n_10250.java, baekjoon/shim/Java/알고리즘_분류/기본_수학_1/n_1193.java, baekjoon/shim/Java/알고리즘_분류/기본_수학_1/n_2869.java, baekjoon/shim/Python/알고리즘_분류/기본_수학_1/n_10250.py, baekjoon/shim/Python/알고리즘_분류/기본_수학_1/n_1193.py, baekjoon/shim/Python/알고리즘_분류/기본_수학_1/n_2869.py
(python, java) 2022.05.24 baekjoon 3문제 완료
=> [SJJ]2022.05.24

baekjoon/jieun/220525/10757.py, baekjoon/jieun/220525/2775.py, baekjoon/jieun/220525/2839.py, programmers/jieun/220525/체육복.py
=> [jieun]2022.05.25

baekjoon/shim/Java/알고리즘_분류/기본_수학_1/n_10757.java, baekjoon/shim/Java/알고리즘_분류/기본_수학_1/n_2775.java, baekjoon/shim/Java/알고리즘_분류/기본_수학_1/n_2839.java, baekjoon/shim/Python/알고리즘_분류/기본_수학_1/n_10757.py, baekjoon/shim/Python/알고리즘_분류/기본_수학_1/n_2775.py, baekjoon/shim/Python/알고리즘_분류/기본_수학_1/n_2839.py, programmers/shim/Java/level1/20220525_체육복.java, programmers/shim/Python/level1/20220525_체육복.py
(python, java) 2022.05.25 programmers 완료, baekjoon 3문제 완료
=> [SJJ]2022.05.25

baekjoon/shim/Java/알고리즘_분류/기본_수학_2/n_11653.java, baekjoon/shim/Java/알고리즘_분류/기본_수학_2/n_1978.java, baekjoon/shim/Java/알고리즘_분류/기본_수학_2/n_2581.java, baekjoon/shim/Python/알고리즘_분류/기본_수학_2/n_11653.py, baekjoon/shim/Python/알고리즘_분류/기본_수학_2/n_1978.py, baekjoon/shim/Python/알고리즘_분류/기본_수학_2/n_2581.py, programmers/shim/Java/level1/20220526_폰켓몬.java, programmers/shim/Python/level1/20220526_폰켓몬.py
(python, java) 2022.05.26 programmers 완료, baekjoon 3문제 완료
=> [SJJ]2022.05.26

baekjoon/shim/Java/알고리즘_분류/기본_수학_2/n_1929.java, baekjoon/shim/Java/알고리즘_분류/기본_수학_2/n_4948.java, baekjoon/shim/Java/알고리즘_분류/기본_수학_2/n_9020.java, baekjoon/shim/Python/알고리즘_분류/기본_수학_2/n_1929.py, baekjoon/shim/Python/알고리즘_분류/기본_수학_2/n_4948.py, baekjoon/shim/Python/알고리즘_분류/기본_수학_2/n_9020.py, programmers/shim/Java/level1/20220527_약수의_개수와_덧셈.java, programmers/shim/Python/level1/20220527_약수의_개수와_덧셈.py
(python, java) 2022.05.27 programmers 완료, baekjoon 3문제 완료
=> [SJJ]2022.05.27

baekjoon/shim/Java/알고리즘_분류/재귀/n_11729.java, baekjoon/shim/Java/알고리즘_분류/재귀/n_2447.java, baekjoon/shim/Python/알고리즘_분류/재귀/n_11729.py, baekjoon/shim/Python/알고리즘_분류/재귀/n_2447.py, programmers/shim/Java/level1/20220531_예산.java, programmers/shim/Python/level1/20220531_예산.py
(python, java) 2022.05.31 programmers 완료, baekjoon 2문제 완료
=> [SJJ]2022.05.31

baekjoon/shim/Java/알고리즘_분류/브루트포스/n_2231.java, baekjoon/shim/Java/알고리즘_분류/브루트포스/n_2798.java, baekjoon/shim/Java/알고리즘_분류/브루트포스/n_7568.java, baekjoon/shim/Python/알고리즘_분류/브루트포스/n_2231.py, baekjoon/shim/Python/알고리즘_분류/브루트포스/n_2798.py, baekjoon/shim/Python/알고리즘_분류/브루트포스/n_7568.py, programmers/shim/Java/level1/20220602_두_개_뽑아서_더하기.java, programmers/shim/Python/level1/20220602_두_개_뽑아서_더하기.py
(python, java) 2022.06.02 programmers 완료, baekjoon 3문제 완료
=> [SJJ]2022.06.02

baekjoon/shim/Java/단계별로_풀어보기/정렬/n_10989.java, baekjoon/shim/Java/단계별로_풀어보기/정렬/n_2750.java, baekjoon/shim/Java/단계별로_풀어보기/정렬/n_2751.java, baekjoon/shim/Python/단계별로_풀어보기/정렬/n_10989.py, baekjoon/shim/Python/단계별로_풀어보기/정렬/n_2750.py, baekjoon/shim/Python/단계별로_풀어보기/정렬/n_2751.py, programmers/shim/Java/level1/20220607_최소직사각형.java, programmers/shim/Python/level1/20220607_최소직사각형.py
(python, java) 2022.06.07 programmers 완료, baekjoon 3문제 완료
=> [SJJ]2022.06.07

baekjoon/shim/Java/단계별로_풀어보기/정렬/n_1427.java, baekjoon/shim/Java/단계별로_풀어보기/정렬/n_2108.java, baekjoon/shim/Python/단계별로_풀어보기/정렬/n_1427.py, baekjoon/shim/Python/단계별로_풀어보기/정렬/n_2108.py, programmers/shim/Java/level1/20220608_나머지가_1이_되는_수_찾기.java, programmers/shim/Python/level1/20220608_나머지가_1이_되는_수_찾기.py
(python, java) 2022.06.08 programmers 완료, baekjoon 2문제 완료
=> [SJJ]2022.06.08

baekjoon/shim/Java/단계별로_풀어보기/집합과_맵/n_10815.java, baekjoon/shim/Java/단계별로_풀어보기/집합과_맵/n_14425.java, baekjoon/shim/Python/단계별로_풀어보기/집합과_맵/n_10815.py, baekjoon/shim/Python/단계별로_풀어보기/집합과_맵/n_14425.py, programmers/shim/Java/level1/같은_숫자는_싫어_20220613.java, programmers/shim/Python/level1/같은_숫자는_싫어_20220613.py
(python, java) 2022.06.13 programmers 완료, baekjoon 2문제 완료
=> [SJJ]2022.06.13

baekjoon/shim/Java/단계별로_풀어보기/집합과_맵/n_10816.java, baekjoon/shim/Java/단계별로_풀어보기/집합과_맵/n_1620.java, baekjoon/shim/Java/단계별로_풀어보기/집합과_맵/n_1764.java, baekjoon/shim/Python/단계별로_풀어보기/집합과_맵/n_10816.py, baekjoon/shim/Python/단계별로_풀어보기/집합과_맵/n_1620.py, baekjoon/shim/Python/단계별로_풀어보기/집합과_맵/n_1764.py, programmers/shim/Java/level1/나누어_떨어지는_숫자_배열_20220614.java, programmers/shim/Python/level1/나누어_떨어지는_숫자_배열_20220614.py
(python, java) 2022.06.14 programmers 완료, baekjoon 3문제 완료
=> [SJJ]2022.06.14

baekjoon/shim/Java/단계별로_풀어보기/집합과_맵/n_11478.java, baekjoon/shim/Java/단계별로_풀어보기/집합과_맵/n_1269.java, baekjoon/shim/Python/단계별로_풀어보기/집합과_맵/n_11478.py, baekjoon/shim/Python/단계별로_풀어보기/집합과_맵/n_1269.py, programmers/shim/Java/level1/두_정수_사이의_합_20220615.java, programmers/shim/Python/level1/두_정수_사이의_합_20220615.py
(python, java) 2022.06.15 programmers 완료, baekjoon 2문제 완료
=> [SJJ]2022.06.15

baekjoon/shim/Java/단계별로_풀어보기/기하/n_1085.java, baekjoon/shim/Java/단계별로_풀어보기/기하/n_3009.java, baekjoon/shim/Java/단계별로_풀어보기/기하/n_4153.java, baekjoon/shim/Python/단계별로_풀어보기/기하/n_1085.py, baekjoon/shim/Python/단계별로_풀어보기/기하/n_3009.py, baekjoon/shim/Python/단계별로_풀어보기/기하/n_4153.py, programmers/shim/Java/level1/문자열_내_마음대로_정렬하기_20220616.java, programmers/shim/Python/level1/문자열_내_마음대로_정렬하기_20220616.py
(python, java) 2022.06.16 programmers 완료, baekjoon 3문제 완료
=> [SJJ]2022.06.16

baekjoon/shim/Java/단계별로_풀어보기/기하/n_1002.java, baekjoon/shim/Java/단계별로_풀어보기/기하/n_2477.java, baekjoon/shim/Java/단계별로_풀어보기/기하/n_3053.java, baekjoon/shim/Python/단계별로_풀어보기/기하/n_1002.py, baekjoon/shim/Python/단계별로_풀어보기/기하/n_2477.py, baekjoon/shim/Python/단계별로_풀어보기/기하/n_3053.py, programmers/shim/Java/level1/문자열_내_p와_y의_개수_20220617.java, programmers/shim/Python/level1/문자열_내_p와_y의_개수_20220617.py
(python, java) 2022.06.17 programmers 완료, baekjoon 3문제 완료
=> [SJJ]2022.06.17

baekjoon/shim/Java/단계별로_풀어보기/기하/n_1358.java, baekjoon/shim/Python/단계별로_풀어보기/기하/n_1004.py, baekjoon/shim/Python/단계별로_풀어보기/기하/n_1358.py, programmers/shim/Java/level1/문자열_내림차순으로_배치하기_20220620.java, programmers/shim/Python/level1/문자열_내림차순으로_배치하기_20220620.py
(python, java) 2022.06.20 programmers 완료, baekjoon 1문제 완료
java 1004 풀어야함
=> [SJJ]2022.06.20

baekjoon/shim/Python/단계별로_풀어보기/정수론_및_조합론/n_1934.py, baekjoon/shim/Python/단계별로_풀어보기/정수론_및_조합론/n_2981.py, baekjoon/shim/Python/단계별로_풀어보기/정수론_및_조합론/n_3036.py, programmers/shim/Python/level1/서울에서_김서방_찾기_20220622.py
(python,) 2022.06.22 programmers 완료, baekjoon 3문제 완료
=> [SJJ]2022.06.22

baekjoon/shim/Java/단계별로_풀어보기/정수론_및_조합론/n_1010.java, baekjoon/shim/Java/단계별로_풀어보기/정수론_및_조합론/n_11050.java, baekjoon/shim/Java/단계별로_풀어보기/정수론_및_조합론/n_11051.java, baekjoon/shim/Python/단계별로_풀어보기/정수론_및_조합론/n_1010.py, baekjoon/shim/Python/단계별로_풀어보기/정수론_및_조합론/n_11050.py, baekjoon/shim/Python/단계별로_풀어보기/정수론_및_조합론/n_11051.py, programmers/shim/Java/level1/소수_찾기_20220623.java, programmers/shim/Python/level1/소수_찾기_20220623.py
(python, java) 2022.06.23 programmers 완료, baekjoon 3문제 완료
=> [SJJ]2022.06.23

baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_1904.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_24416.java, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_1904.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_24416.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_9184.py, programmers/shim/Java/level1/이상한_문자_만들기_20220704.java, programmers/shim/Python/level1/이상한_문자_만들기_20220704.py
(python, java) 2022.07.04 programmers, baekjoon 완료 (java 9184 제외)
=> [SJJ]2022.07.04

baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_1149.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_1463.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_1912.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_1932.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_2579.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_9461.java, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_1149.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_1463.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_1912.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_1932.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_2579.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_9461.py, programmers/shim/Java/level1/자릿수_더하기_20220705.java, programmers/shim/Java/level1/자연수_뒤집어_배열로_만들기_20220705.java, programmers/shim/Python/level1/자릿수_더하기_20220705.py, programmers/shim/Python/level1/자연수_뒤집어_배열로_만들기_20220705.py
(python, java) 2022.07.05~06 programmers 2문제 완료, baekjoon 6문제 완료
=> [SJJ]2022.07.06

baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_10844.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_11053.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_11054.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_2156.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_2565.java, baekjoon/shim/Java/단계별로_풀어보기/정수론_및_조합론/n_1934.java, baekjoon/shim/Java/단계별로_풀어보기/정수론_및_조합론/n_2981.java, baekjoon/shim/Java/단계별로_풀어보기/정수론_및_조합론/n_3036.java, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_10844.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_11053.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_11054.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_2156.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_2565.py, programmers/shim/Java/level1/서울에서_김서방_찾기_20220622.java, programmers/shim/Java/level1/정수_내림차순으로_배치하기_20220707.java, programmers/shim/Java/level1/정수_제곱근_판별_20220707.java, programmers/shim/Python/level1/정수_내림차순으로_배치하기_20220707.py, programmers/shim/Python/level1/정수_제곱근_판별_20220707.py
(python, java) 2022.07.08~11 programmers 2문제 완료, baekjoon 5문제 완료
2022.06.22 java programmers 1문제 완료, beakjoon 3문제 완료
=> [SJJ]2022.07.11

baekjoon/shim/Java/단계별로_풀어보기/누적_합/n_11659.java, baekjoon/shim/Java/단계별로_풀어보기/누적_합/n_16139.java, baekjoon/shim/Java/단계별로_풀어보기/누적_합/n_2559.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_12865.java, baekjoon/shim/Java/단계별로_풀어보기/동적_계획법1/n_9251.java, baekjoon/shim/Python/단계별로_풀어보기/누적_합/n_11659.py, baekjoon/shim/Python/단계별로_풀어보기/누적_합/n_16139.py, baekjoon/shim/Python/단계별로_풀어보기/누적_합/n_2559.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_12865.py, baekjoon/shim/Python/단계별로_풀어보기/동적_계획법1/n_9251.py, programmers/shim/Java/level1/제일_작은_수_제거하기_20220711.java, programmers/shim/Java/level1/짝수와_홀수_20220711.java, programmers/shim/Python/level1/제일_작은_수_제거하기_20220711.py, programmers/shim/Python/level1/짝수와_홀수_20220711.py
(python, java) 2022.07.12~13 programmers 2문제 완료, baekjoon 5문제 완료
programmers 문제 11일에 풀어서 날짜 11일로 적혀있음
=> [SJJ]2022.07.13

baekjoon/shim/Java/단계별로_풀어보기/그리디_알고리즘/n_11047.java, baekjoon/shim/Java/단계별로_풀어보기/그리디_알고리즘/n_11399.java, baekjoon/shim/Java/단계별로_풀어보기/누적_합/n_11660.java, baekjoon/shim/Python/단계별로_풀어보기/그리디_알고리즘/n_11047.py, baekjoon/shim/Python/단계별로_풀어보기/그리디_알고리즘/n_11399.py, baekjoon/shim/Python/단계별로_풀어보기/누적_합/n_11660.py, programmers/shim/Java/level1/최대공약수와_최소공배수_20220713.java, programmers/shim/Java/level1/콜라츠_추측_20220713.java, programmers/shim/Python/level1/최대공약수와_최소공배수_20220713.py, programmers/shim/Python/level1/콜라츠_추측_20220713.py
(python, java) 2022.07.18 programmers 2문제 완료, baekjoon 3문제 완료 10986, 1931 풀어야 함
=> [SJJ]2022.07.18

baekjoon/shim/Java/단계별로_풀어보기/기하/n_1002.java, baekjoon/shim/Java/단계별로_풀어보기/기하/n_2477.java, baekjoon/shim/Java/단계별로_풀어보기/기하/n_3053.java, baekjoon/shim/Java/단계별로_풀어보기/정수론_및_조합론/n_2981.java, baekjoon/shim/Python/단계별로_풀어보기/기하/n_1002.py, baekjoon/shim/Python/단계별로_풀어보기/기하/n_2477.py, baekjoon/shim/Python/단계별로_풀어보기/기하/n_3053.py, baekjoon/shim/Python/단계별로_풀어보기/정수론_및_조합론/n_2981.py
(python, java) 2022.07.20 baekjoon 4문제 완료
=> [SJJ]2022.07.20

baekjoon/shim/Java/단계별로_풀어보기/그리디_알고리즘/n_13305.java, baekjoon/shim/Java/단계별로_풀어보기/그리디_알고리즘/n_1541.java, baekjoon/shim/Java/단계별로_풀어보기/스택/n_10773.java, baekjoon/shim/Java/단계별로_풀어보기/스택/n_10828.java, baekjoon/shim/Java/단계별로_풀어보기/스택/n_9012.java, baekjoon/shim/Python/단계별로_풀어보기/그리디_알고리즘/n_13305.py, baekjoon/shim/Python/단계별로_풀어보기/그리디_알고리즘/n_1541.py, baekjoon/shim/Python/단계별로_풀어보기/스택/n_10773.py, baekjoon/shim/Python/단계별로_풀어보기/스택/n_10828.py, baekjoon/shim/Python/단계별로_풀어보기/스택/n_9012.py, programmers/shim/Java/level1/평균_구하기_20220720.java, programmers/shim/Java/level1/하샤드_수_20220720.java, programmers/shim/Python/level1/평균_구하기_20220720.py, programmers/shim/Python/level1/하샤드_수_20220720.py
(python, java) 2022.07.22 programmers 2문제 완료, baekjoon 5문제 완료
=> [SJJ]2022.07.22
